baseurl: "/cleanify-design" # the subpath of your site, e.g. /blog
title: "Cleanify Design" # the name of your site, e.g. ACME Corp.

destination: docs
source: "site"

sass:
  style: compressed

collections:
  latest          :
    output    : true
    permalink : /v2/docs/:path/
  lts          :
    output    : true
    permalink : /v1/docs/:path/